# Generated by Django 5.0.14 on 2026-01-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Математика, Сложение', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия. Используется в URL', max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории для SEO', verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, help_text='Иконка для отображения в меню', null=True, upload_to='categories/icons/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные категории скрыты на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, help_text='Оставьте пустым для главной категории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='categories__parent__85acd9_idx'), models.Index(fields=['order'], name='categories__order_b7cb6e_idx')],
            },
        ),
    ]
