# Generated by Django 5.0.14 on 2026-01-26 16:29

from django.db import migrations


def translate_categories(apps, schema_editor):
    """Перевести названия категорий на русский язык"""
    Category = apps.get_model('categories', 'Category')

    translations = {
        'home': ('Главная', 'Домашняя страница'),
        'worksheet-generator': ('Генератор рабочих листов', 'Создавайте собственные рабочие листы'),
        'alphabets': ('Алфавит', 'Изучение букв и алфавита'),
        'numbers': ('Цифры', 'Изучение цифр и чисел'),
        'maths': ('Математика', 'Математические задания'),
        'vocabulary': ('Словарный запас', 'Развитие словарного запаса'),
        'shapes': ('Фигуры', 'Изучение геометрических фигур'),
        'coloring': ('Раскраски', 'Раскраски для детей'),
        'dot-to-dot': ('Соедини точки', 'Соединяй точки по порядку'),
        'drawing': ('Рисование', 'Упражнения по рисованию'),
        'gk': ('Общие знания', 'Расширение кругозора'),
        'body-parts': ('Части тела', 'Изучение частей тела'),
        'cartoon-stickers': ('Мультяшные стикеры', 'Стикеры с мультяшными персонажами'),
        'patterns': ('Узоры', 'Работа с узорами и последовательностями'),
        'flash-cards': ('Флеш-карточки', 'Обучающие карточки'),
        'telling-time': ('Определение времени', 'Учимся определять время'),
        'tracing-lines': ('Обводка линий', 'Обводка и прорисовка линий'),
        'sliding-puzzle': ('Пазлы-головоломки', 'Пазлы и головоломки'),
        'origami': ('Оригами', 'Искусство складывания бумаги'),
        'mazes': ('Лабиринты', 'Прохождение лабиринтов'),
        'practice-writing-letters': ('Практика письма букв', 'Учимся писать буквы'),
        'cursive-handwriting-practice': ('Прописи', 'Прописные буквы'),
        'missing-letters': ('Пропущенные буквы', 'Найди пропущенную букву'),
        'practice-writing-numbers': ('Практика письма цифр', 'Учимся писать цифры'),
        'missing-numbers': ('Пропущенные цифры', 'Найди пропущенную цифру'),
        'addition': ('Сложение', 'Примеры на сложение'),
        'subtraction': ('Вычитание', 'Примеры на вычитание'),
        'multiplication': ('Умножение', 'Примеры на умножение'),
        'multiplication-chart': ('Таблица умножения', 'Таблица умножения'),
        'division': ('Деление', 'Примеры на деление'),
        'counting': ('Счёт', 'Учимся считать'),
        'word-search': ('Поиск слов', 'Найди слова в таблице'),
        'crossword-puzzle': ('Кроссворд', 'Разгадай кроссворд'),
        'spelling-word-scramble': ('Анаграммы', 'Собери слово из букв'),
        'sight-words': ('Часто встречающиеся слова', 'Популярные слова'),
        'english-worksheets': ('Английский язык', 'Задания по английскому языку'),
        'digraph-spelling-worksheets': ('Орфография', 'Правописание диграфов'),
        'picture-shadow-matching': ('Найди тень', 'Сопоставь картинку с тенью'),
        'find-the-same': ('Найди одинаковое', 'Найди одинаковые предметы'),
        'find-the-difference': ('Найди отличия', 'Найди различия между картинками'),
    }

    for slug, (name_ru, description_ru) in translations.items():
        Category.objects.filter(slug=slug).update(
            name=name_ru,
            description=description_ru
        )


def reverse_translate_categories(apps, schema_editor):
    """Откатить перевод обратно на английский"""
    # Оставляем пустым, так как откат не критичен
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(translate_categories, reverse_translate_categories),
    ]
