# Generated by Django 5.0.14 on 2026-01-25 17:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Краткое описание проекта (1-2 предложения)', verbose_name='Краткое описание')),
                ('body', wagtail.fields.RichTextField(help_text='Подробное описание проекта, его целей и задач', verbose_name='Полное описание')),
                ('mission', wagtail.fields.RichTextField(blank=True, help_text='Описание миссии проекта', verbose_name='Наша миссия')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в футере')),
            ],
            options={
                'verbose_name': 'Страница "О проекте"',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(help_text='Текст страницы контактов', verbose_name='Основной текст')),
                ('email', models.EmailField(blank=True, help_text='Контактный email (опционально, если отличается от основного)', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон (опционально, если отличается от основного)', max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, help_text='Физический адрес офиса/организации', verbose_name='Адрес')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в футере')),
            ],
            options={
                'verbose_name': 'Страница контактов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(help_text='Основное содержимое страницы (поддерживает форматирование)', verbose_name='Содержимое')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Добавить ссылку на эту страницу в футер сайта', verbose_name='Показывать в футере')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(help_text='Полный текст правил использования контента сайта', verbose_name='Правила использования')),
                ('last_updated', models.DateField(blank=True, help_text='Когда правила были обновлены последний раз', null=True, verbose_name='Дата последнего обновления')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в футере')),
            ],
            options={
                'verbose_name': 'Правила использования контента',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Умные листочки', help_text='Основной заголовок на главной странице', max_length=200, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Дополнительный текст под заголовком', max_length=300, verbose_name='Подзаголовок Hero')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Текст-описание сайта под Hero секцией', verbose_name='Вводный текст')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Фоновое изображение для Hero секции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero изображение')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, help_text='Основной email для связи с администрацией', max_length=254, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(blank=True, help_text='Основной телефон для связи', max_length=50, verbose_name='Телефон для связи')),
                ('header_text', models.CharField(blank=True, help_text='Короткий текст/слоган отображаемый в шапке сайта', max_length=200, verbose_name='Текст в хедере')),
                ('home_page_intro', wagtail.fields.RichTextField(blank=True, help_text='Текст, отображаемый на главной странице под Hero секцией', verbose_name='Вводный текст на главной')),
                ('footer_text', models.TextField(blank=True, help_text='Текст, отображаемый в футере сайта (копирайт, описание и т.д.)', verbose_name='Текст в футере')),
                ('telegram_url', models.URLField(blank=True, help_text='Ссылка на канал/группу в Telegram', verbose_name='Telegram')),
                ('worksheets_per_page', models.PositiveIntegerField(default=20, help_text='Количество рабочих листов на одной странице каталога', verbose_name='Рабочих листов на странице')),
                ('show_stats', models.BooleanField(default=True, help_text='Отображать счетчики просмотров и скачиваний', verbose_name='Показывать статистику')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
