# Generated by Django 5.0.14 on 2026-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: математика, сложение, раскраски', max_length=100, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия', max_length=100, unique=True, verbose_name='URL slug')),
                ('description', models.CharField(blank=True, help_text='Краткое описание тега для SEO', max_length=300, verbose_name='Описание')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Автоматически обновляется при добавлении/удалении тега', verbose_name='Количество использований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['-usage_count'], name='tags_tag_usage_c_be8d76_idx'), models.Index(fields=['slug'], name='tags_tag_slug_dcb0c2_idx')],
            },
        ),
    ]
