# Generated by Django 5.0.14 on 2026-01-26 16:37

from django.db import migrations


def translate_tags(apps, schema_editor):
    """Перевести названия тегов на русский язык"""
    Tag = apps.get_model('tags', 'Tag')

    translations = {
        'age-3-4': 'Возраст 3-4 года',
        'age-5-6': 'Возраст 5-6 лет',
        'age-7-8': 'Возраст 7-8 лет',
        'age-9-10': 'Возраст 9-10 лет',
        'animals': 'Животные',
        'black-white': 'Чёрно-белое',
        'colorful': 'Цветное',
        'colors': 'Цвета',
        'creative': 'Творческое',
        'easy': 'Лёгкий',
        'educational': 'Образовательное',
        'fun': 'Весёлое',
        'grade-1': '1 класс',
        'grade-2': '2 класс',
        'grade-3': '3 класс',
        'hard': 'Сложный',
        'kindergarten': 'Детский сад',
        'letters': 'Буквы',
        'medium': 'Средний',
        'nature': 'Природа',
        'numbers': 'Цифры',
        'practice': 'Практика',
        'preschool': 'Дошкольники',
        'shapes': 'Фигуры',
    }

    for slug, name_ru in translations.items():
        Tag.objects.filter(slug=slug).update(name=name_ru)


def reverse_translate_tags(apps, schema_editor):
    """Откатить перевод обратно на английский"""
    # Оставляем пустым, так как откат не критичен
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(translate_tags, reverse_translate_tags),
    ]
