# Generated by Django 5.0.14 on 2026-01-25 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Сложение чисел в пределах 10', max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия', max_length=300, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(help_text='Подробное описание рабочего листа', verbose_name='Описание')),
                ('grade_level', models.CharField(choices=[('preschool', 'Дошкольники (3-4 года)'), ('kindergarten', 'Подготовительная группа (5-6 лет)'), ('grade1', '1 класс'), ('grade2', '2 класс'), ('grade3', '3 класс'), ('grade4', '4 класс'), ('grade5', '5 класс')], help_text='Для какого возраста/класса предназначен', max_length=20, verbose_name='Уровень обучения')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('pdf_file', models.FileField(help_text='Рабочий лист в формате PDF для печати', upload_to='worksheets/pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF файл')),
                ('thumbnail', models.ImageField(blank=True, help_text='Автоматически генерируется из PDF (300x400px)', null=True, upload_to='worksheets/thumbnails/%Y/%m/', verbose_name='Миниатюра для каталога')),
                ('preview_image', models.ImageField(blank=True, help_text='Автоматически генерируется из PDF (800x1000px)', null=True, upload_to='worksheets/previews/%Y/%m/', verbose_name='Превью для карточки')),
                ('meta_title', models.CharField(blank=True, help_text='Если не указан, используется title', max_length=200, verbose_name='SEO заголовок')),
                ('meta_description', models.CharField(blank=True, help_text='Краткое описание для поисковых систем', max_length=300, verbose_name='SEO описание')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Увеличивается при открытии карточки', verbose_name='Количество просмотров')),
                ('downloads_count', models.PositiveIntegerField(default=0, help_text='Увеличивается при скачивании PDF', verbose_name='Количество скачиваний')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображать на главной странице', verbose_name='Избранный')),
                ('is_published', models.BooleanField(default=True, help_text='Неопубликованные листы скрыты от пользователей', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(help_text='Выберите категорию (предпочтительно 2-го уровня)', on_delete=django.db.models.deletion.PROTECT, related_name='worksheets', to='categories.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, help_text='Выберите теги для этого рабочего листа', related_name='worksheets', to='tags.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рабочий лист',
                'verbose_name_plural': 'Рабочие листы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='worksheets__created_bb6c24_idx'), models.Index(fields=['category', '-created_at'], name='worksheets__categor_792bf7_idx'), models.Index(fields=['grade_level'], name='worksheets__grade_l_e19b5c_idx'), models.Index(fields=['is_featured', '-created_at'], name='worksheets__is_feat_d72eb9_idx'), models.Index(fields=['is_published'], name='worksheets__is_publ_a3bdf4_idx')],
            },
        ),
    ]
